title: The International Workshop of CoDesign 2024
description: November 9-11, 2024, in Osaka, Japan
theme: jekyll-theme-slate
show_downloads: false
google_analytics: 280783166
github:
  is_project_page: false